# Generated by Django 4.1.7 on 2023-03-28 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pii', '0002_versiya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versiya',
            old_name='url',
            new_name='link',
        ),
    ]
